### ISSUE TITLE
Cannot compile with brunch 2.10.12

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact-frontend#77]
When trying to compile with brunch 2.10.12, the following error pops out:

```
09:10:54 - info: compiling
09:10:58 - info: compiling.
/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-map-generator.js:289
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":574,"column":10},"source":"node_modules/bulma/sass/utilities/controls.sass","original":{"line":26,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-node.js:351:13
    at SourceNode_walk [as walk] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_walk [as walk] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/node_modules/source-map/lib/source-node.js:342:8)
    at concat (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/fs_utils/generate.js:125:15)
    at generate (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/fs_utils/generate.js:181:14)
    at Promise.all.changed.map.file (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/fs_utils/write.js:166:12)
    at Array.map (native)
    at write (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/fs_utils/write.js:165:30)
    at BrunchWatcher.compile (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/watch.js:293:5)
    at FileList.fileList.on (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/watch.js:154:14)
    at emitNone (events.js:86:13)
    at FileList.emit (events.js:185:7)
    at Timeout.timer.setTimeout [as _onTimeout] (/root/.nvm/versions/node/v6.12.3/lib/node_modules/brunch/lib/fs_utils/file_list.js:171:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by Betree** [comment]
This is not intended to be fixed as we will be [moving to webpack](https://trello.com/c/NrJVTVP7/561-migrate-to-webpack) soon.
